#spring.application.name=demoTorneoSpringBatch
spring:
  datasource-torneo:
    jdbcUrl: jdbc:postgresql://localhost:5432/torneodemobatch
    username: postgres
    password: example
    driver-class-name: org.postgresql.Driver
