#spring.application.name=demoTorneoSpringBatch
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/torneodemobatch
    username: postgres
    password: example
    driverClassName: org.postgresql.Driver