spring.application.name=torneoDemo
spring.datasource.url=jdbc:postgresql://localhost:5432/torneo
spring.datasource.username=postgres
spring.datasource.password=example
spring.datasource.driver-class-name=org.postgresql.Driver
spring.profiles.active=${IMPLEMENTAZIONE_DAO_TORNEO}
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.springframework.transaction=DEBUG
logging.level.root=INFO
logging.level.your.package.name=DEBUG
